### ISSUE TITLE
Diapositive utilizzati all'interno della presentazione

### ISSUE THREAD

**Issue by sunnyxraj** [AltenITALIA/ContosoSpareParts#2]
Ciao ragazzi, posso chiedervi dove sono stati caricate le diapositive utilizzate nella presentazione?

**Comment by rcappello** [comment]
Ciao! Abbiamo inviato i deck all'email di registrazione di Eventbrite lunedì, se non le hai ricevute contattami privatamente che ti giro il link (trovi i contatti nel sito nel mio profilo utente).
